### ISSUE TITLE
A neural transducer

### ISSUE THREAD

**Issue by Nitinsiwach** [the-deep-learners/study-group#21]
Link to follow: (A neural transducer by Navdeep Jaitly and google brain team)  (https://arxiv.org/pdf/1511.04868.pdf)
query is from section 3.5

Can some light please be shed by someone on how the equation 10 leads to equation 11?

**Comment by jonkrohn** [comment]
Hi @Nitinsiwach this "issue" is not related to any code in this repository. Cross Validated (https://stats.stackexchange.com/) is a more appropriate venue for your question.
